

GET https://api.github.com
Accept: application/vnd.github.v3+json

###
GET https://api.github.com/users/sgshubham98
Authorization: Token 


###
GET https://api.github.com/repos/sgshubham98/android-messaging/commits

###
GET https://api.github.com/repos/Ayush783/Coronavirus_tracker_app/commits

###
GET https://api.github.com/users/sgshubham98/starred